In [1]:
def count_uppercase (string):
    num_upper=0
    for char in string:
        if not char.isupper():
            continue
            num_upper += 1
        return num_upper
    
def count_uppercase_2(string):
    num_upper = 0
    for char in string:
        if not char.isupper():
            num_upper += 1
        return num_upper

def count_lowercase(string):
    num_upper = 0
    for char in string:
        if not char.islower():
            continue
            num_upper += 1
        return num_upper

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy

In [4]:
conda list numpy

# packages in environment at /Users/rinanamiradalimunthe/opt/anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.18.5           py38h1da2735_0  
numpy-base                1.18.5           py38h3304bdc_0  
numpydoc                  1.1.0                      py_0  

Note: you may need to restart the kernel to use updated packages.


In [5]:
np.__version__

NameError: name 'np' is not defined

In [7]:
import numpy as np
np.__version__

'1.18.5'

In [10]:
arr3 = np.array ([
    [[1,2,3],[11,22,33]],[[4,5,6],[44,55,66]]])
print (arr3)

[[[ 1  2  3]
  [11 22 33]]

 [[ 4  5  6]
  [44 55 66]]]


In [11]:
print(arr1)

NameError: name 'arr1' is not defined

In [14]:
import numpy as np
a = np.array ([[20,1]])

In [17]:
import pandas as pd

In [1]:
import pandas as pd

In [5]:
pip install --upgrade pandas

Requirement already up-to-date: pandas in /Users/rinanamiradalimunthe/opt/anaconda3/lib/python3.8/site-packages (1.1.3)
Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install --upgrade pandas

Requirement already up-to-date: pandas in /Users/rinanamiradalimunthe/opt/anaconda3/lib/python3.8/site-packages (1.1.3)
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
pd.__version__

'1.1.3'